theme: minima
title: Nicolas Page
author: Francis Ford Copola's Sister
/* Full size background image */
html, #container, .inner { background-color:transparent;}
html {
  background:url(background.jpg) center center no-repeat fixed;
  background-size:cover;
  }
